chunking_config:
  chunk_overlap_tokens: 256
  chunk_size_tokens: 1024
  class_path: __main__.RecursiveTextSplitterChunkingConfig
  embedding_model_endpoint: databricks-gte-large-en
class_path: __main__.DataPipelineConfig
output:
  chunked_docs_table: '`nasa-test`.`default`.`resumes_docs_chunked`'
  class_path: __main__.DataPipelineOutputConfig
  parsed_docs_table: '`nasa-test`.`default`.`resumes_docs`'
  vector_index: nasa-test.default.resumes_docs_chunked_index
  vector_search_endpoint: product-docs-vs-endpoint
source:
  class_path: __main__.UCVolumeSourceConfig
  uc_catalog_name: nasa-test
  uc_schema_name: default
  uc_volume_name: resumes
  volume_path: /Volumes/nasa-test/default/resumes
  volume_uc_fqn: nasa-test.default.resumes
